# Generated by Django 4.1 on 2022-09-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_requestt_options_alter_requestt_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinerequest',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='onlinerequest',
            old_name='request_id',
            new_name='request',
        ),
    ]
